Fallback to bundler 1.7.13
Bundler 2 requires Ruby 2.3.0 or higher
https://travis-ci.org/rsim/ruby-plsql/jobs/475857066

```
$ gem install bundler
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.
The command "gem install bundler" failed and exited with 1 during .
```

Refer https://github.com/rails/rails/pull/34851