Skip "using Oracle 9.2" for Oracle Database 18c or higher
Without this skip, this spec will fail as follows.

```
Failures:

  1) Parameter type mapping / Function with table indexed by bynary integer parameter using Oracle 9.2 should create temporary tables when using Oracle 9.2
     Failure/Error: case element_metadata[:data_type]

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./lib/plsql/procedure.rb:314:in `block in ensure_tmp_tables_created'
     # ./lib/plsql/procedure.rb:311:in `each'
     # ./lib/plsql/procedure.rb:311:in `ensure_tmp_tables_created'
     # ./lib/plsql/procedure_call.rb:15:in `initialize'
     # ./lib/plsql/procedure.rb:545:in `new'
     # ./lib/plsql/procedure.rb:545:in `exec'
     # ./lib/plsql/package.rb:67:in `method_missing'
     # ./spec/plsql/procedure_spec.rb:1522:in `block (4 levels) in <top (required)>'

Finished in 44.29 seconds (files took 0.56531 seconds to load)
453 examples, 1 failure, 3 pending

Failed examples:

rspec ./spec/plsql/procedure_spec.rb:1521 # Parameter type mapping / Function with table indexed by bynary integer parameter using Oracle 9.2 should create temporary tables when using Oracle 9.2
```

Here is the reason why:
This spec simulates the connection as if it connects to Oracle database 9.2.

https://github.com/rsim/ruby-plsql/blob/4c336819759d08c076eb0c351620f21eb5225161/spec/plsql/procedure_spec.rb#L1512-L1514

```ruby
 # simulate Oracle 9.2 connection
 plsql(:oracle_9).connection = get_connection
 allow(plsql(:oracle_9).connection).to receive(:database_version).and_return([9, 2, 0, 0])
```

Then `get_argument_metadata` executes `get_argument_metadata_below_18c`.

https://github.com/rsim/ruby-plsql/blob/4c336819759d08c076eb0c351620f21eb5225161/lib/plsql/procedure.rb#L85-L91

```ruby
 def get_argument_metadata #:nodoc:
   if (@schema.connection.database_version <=> [18, 0, 0, 0]) >= 0
     get_argument_metadata_from_18c
   else
     get_argument_metadata_below_18c
   end
 end
```

Both `get_argument_metadata_from_18c` and `get_argument_metadata_below_18c` methods depend on each Oracle database dictionary implentation then only mocking database version is not enough.